# Estruturas de Repetição - WHILE

In [10]:
from colorama import Fore, Style
import numpy as np

In [6]:
numero = 1

while numero < 6:
    print(numero)
    numero += 1

1
2
3
4
5


In [2]:
numero = 5

while numero > 0:
    print(numero)
    numero -= 1

5
4
3
2
1


In [4]:
soma = 0
numero = 1

while numero < 6:
    soma += numero
    numero += 1

print(soma)

15


In [5]:
numero = 12

while numero < 1 or numero > 10:
    numero = int(input("Digite um numero: "))

    pergunta = int(input("Caso deseje sair da aplicação digite entre 1 e 10: "))

Digite um numero:  10
Caso deseje sair da aplicação digite entre 1 e 10:  4


In [7]:
tupla = { 'Joao', 'kayque', 'Joao', 'kayque', 'Joao', }

tupla

{'Joao', 'kayque'}

In [8]:
tupla.remove("kayque")

In [9]:
tupla

{'Joao'}

In [10]:
alunos = { "Aruane": 27, "João Kleber": 18, "Kayque Gay": 18, "Ricardo Souzas": 18 }

alunos

{'Aruane': 27, 'João Kleber': 18, 'Kayque Gay': 18, 'Ricardo Souzas': 18}

In [11]:
alunos.keys()

dict_keys(['Aruane', 'João Kleber', 'Kayque Gay', 'Ricardo Souzas'])

In [12]:
alunos.values()

dict_values([27, 18, 18, 18])

In [15]:
for C, V in alunos.items():
    print(C, V)

Aruane 27
João Kleber 18
Kayque Gay 18
Ricardo Souzas 18


In [3]:
import numpy as np

In [4]:
matriz = np.array ([[23,3,1,42],
                    [4,53,62,4],
                    [4,52,63,4]
                   ])


In [18]:
matriz

array([[2, 3, 1],
       [4, 5, 6]])

In [19]:
matriz.shape

(2, 3)

In [118]:


print(Fore.BLACK + "Legal")

matriz

Legal


array([[2, 3, 1],
       [4, 5, 6]])

In [17]:
for linha in range(matriz.shape[0]):
   for coluna in range(matriz.shape[1]):
        print(Fore.RED + f'{matriz[linha][coluna]}')

23
3
1
42
4
53
62
4
4
52
63
4


In [160]:
ajuda = 'Verde = Linha'
ajuda1 = 'Vermelho = Coluna'

print(ajuda, ajuda1)

for linha in range(matriz.shape[0]):
    for coluna in range(matriz.shape[1]):
        print(Fore.GREEN + f'{linha}', Fore.RED + f'{coluna}')

Verde = Linha Vermelho = Coluna
0 0
0 1
0 2
0 3
1 0
1 1
1 2
1 3
2 0
2 1
2 2
2 3


In [16]:
for coluna in range(matriz.shape[1]):
    for linha in range(matriz.shape[0]):
        print(Fore.RED + f'{matriz[linha][coluna]}')

23
4
4
3
53
52
1
62
63
42
4
4


In [18]:
matriz1 = np.array ([[1,2,3]])
matriz2 = np.array ([[3,2,1]])

print(matriz1 + matriz2)

[[4 4 4]]
